apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: synthetic-ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.108.0
          args:
            - --config=/etc/otelcol-contrib/config.yaml
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-config
